CREATE TABLE Vehicles (
    VehicleID INT PRIMARY KEY AUTO_INCREMENT,
    Make VARCHAR(50) NOT NULL,
    Model VARCHAR(50) NOT NULL,
    Year INT CHECK (Year >= 1886),
    Color VARCHAR(30),
    LicensePlate VARCHAR(15) UNIQUE,
    OwnerName VARCHAR(100),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Drivers (
    DriverID INT PRIMARY KEY AUTO_INCREMENT,
    FullName VARCHAR(100) NOT NULL,
    DateOfBirth DATE NOT NULL,
    LicenseNumber VARCHAR(20) UNIQUE NOT NULL,
    LicenseExpiration DATE NOT NULL,
    PhoneNumber VARCHAR(15),
    Email VARCHAR(50),
    Address TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
